openapi: "3.0.0"
info:
  version: 1.0.0
  title: ACME Banking API
paths:
  /customers:
    get:
      responses:
        "200":
          description: Retrieve customer information
        "404":
          description: No customer records found
          content: 
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                  message:
                    type: string
    post:
      requestBody:
        content: {}
      responses:
        "201":
          description: Create customer information
          headers:
            Location:
              schema:
                type: string

  /customers/{customer_id}:
    get:
      responses:
        "200":
          description:
        "404":
          description: No customer records found
          content: 
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                  message:
                    type: string
    delete:
      responses:
        "200":
          description: Archive customer record
    patch:
      requestBody:
        content:
          {}
      responses:
        "204":
          description: |
            Update customer record

            Supplied content does **NOT** need to be
            the entire record, it simply needs to
            contain the _updated_ information

            - item 1
            - item 2
        "503":
          description: 
          content: 
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                  message:
                    type: string  
  
  /customers/{customer_id}/accounts:
    get:
      responses:
        "200":
          description:

  /accounts:
    get:
      responses:
        "200":
          description: Retrieve Account Records
    post:
      requestBody:
        content: {}
      responses:
        "201":
          description: Create account information
          headers:
            Location:
              schema:
                type: string

  /accounts/{account_id}:
    get:
      responses:
        "200":
          description: 
    put:
      requestBody:
        content:
          {}            
      responses:
        "200":
          description: 
        "201":
          description: 
          headers:
            Location:
              schema:
                type: string

  /accounts/{account_id}/transactions:
    get:
      responses:
        "200":
          description: 

  /transactions:
    post:
      requestBody:
        content: {}
      responses:
        "201":
          description: Create transaction information
          headers:
            Location:
              schema:
                type: string

  /transactions/{transaction_id}:
    get:
      responses:
        "200":
          description: Retrieve transaction information for one ID    